
INSERT INTO "PUBLIC"."PRODUCT" VALUES('1', 'Blue Boss', 'apparel', TIMESTAMP '2020-03-20 17:09:06.324377', 'Blue hugo boss shirt', 'Blue Shirt');
INSERT INTO "PUBLIC"."PRODUCT" VALUES('2', 'Blue Boss', 'apparel', TIMESTAMP '2020-03-20 19:10:58.068358', 'Blue hugo boss shirt', 'Blue Shirt');
INSERT INTO "PUBLIC"."PRODUCT" VALUES('3', 'Custom Hugo Boss', 'custom', TIMESTAMP '2020-03-20 19:11:27.408341', 'Custom Yellow hugo boss shirt', 'Custom Yellow Shirt');


INSERT INTO "PUBLIC"."PRODUCT_ENTITY_TAGS" VALUES('1', 'red');
INSERT INTO "PUBLIC"."PRODUCT_ENTITY_TAGS" VALUES('1', 'shirt');
INSERT INTO "PUBLIC"."PRODUCT_ENTITY_TAGS" VALUES('1', 'slim fit');
INSERT INTO "PUBLIC"."PRODUCT_ENTITY_TAGS" VALUES('2', 'red');
INSERT INTO "PUBLIC"."PRODUCT_ENTITY_TAGS" VALUES('2', 'shirt');
INSERT INTO "PUBLIC"."PRODUCT_ENTITY_TAGS" VALUES('2', 'slim fit');
INSERT INTO "PUBLIC"."PRODUCT_ENTITY_TAGS" VALUES('3', 'red');
INSERT INTO "PUBLIC"."PRODUCT_ENTITY_TAGS" VALUES('3', 'shirt');
INSERT INTO "PUBLIC"."PRODUCT_ENTITY_TAGS" VALUES('3', 'slim fit');