;             
CREATE USER IF NOT EXISTS "SA" SALT 'f7acd497c04aed3a' HASH '4cbec2372dd59655ecd036f6c935d056bb3155dd91d60085f34a544dc8a89e7d' ADMIN;         
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_21559626_1D5A_41DB_8B0F_F00885048647" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_D2FB023E_5FC6_44BA_8CE3_F329B7683803" START WITH 4 BELONGS_TO_TABLE;
CREATE MEMORY TABLE "PUBLIC"."PRODUCT_ENTITY_TAGS"(
    "PRODUCT_ENTITY_ID" VARCHAR(255) NOT NULL,
    "TAGS" VARCHAR(255)
);              
-- 9 +/- SELECT COUNT(*) FROM PUBLIC.PRODUCT_ENTITY_TAGS;     
INSERT INTO "PUBLIC"."PRODUCT_ENTITY_TAGS" VALUES('1', 'red');
INSERT INTO "PUBLIC"."PRODUCT_ENTITY_TAGS" VALUES('1', 'shirt');              
INSERT INTO "PUBLIC"."PRODUCT_ENTITY_TAGS" VALUES('1', 'slim fit');           
INSERT INTO "PUBLIC"."PRODUCT_ENTITY_TAGS" VALUES('2', 'red');
INSERT INTO "PUBLIC"."PRODUCT_ENTITY_TAGS" VALUES('2', 'shirt');              
INSERT INTO "PUBLIC"."PRODUCT_ENTITY_TAGS" VALUES('2', 'slim fit');           
INSERT INTO "PUBLIC"."PRODUCT_ENTITY_TAGS" VALUES('3', 'red');
INSERT INTO "PUBLIC"."PRODUCT_ENTITY_TAGS" VALUES('3', 'shirt');              
INSERT INTO "PUBLIC"."PRODUCT_ENTITY_TAGS" VALUES('3', 'slim fit');           
ALTER TABLE "PUBLIC"."PRODUCT_ENTITY_TAGS" ADD CONSTRAINT "PUBLIC"."FKE5W4HCLWYTMJ7JLGI069POEW0" FOREIGN KEY("PRODUCT_ENTITY_ID") REFERENCES "PUBLIC"."PRODUCT"("ID") NOCHECK;
